language: go

go:
  - 1.10.x
  - 1.11.x

services:
  - docker

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y --no-install-recommends build-essential make

script:
  - make all
  - make test
